import { Inter } from "next/font/google";

import Footer from "@/components/start/Footer";
import Header from "@/components/start/Header";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Noa Beach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} scroll-smooth`}>
        <Header />
        <main className="min-h-screen w-full scroll-smooth">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
